Remove duplicated functions in test_full_keyboard.py
Running flake8 on that file reports:

    test_full_keyboard.py:708:1: F811 redefinition of unused 'test_kbhit_no_kb' from line 123
    test_full_keyboard.py:720:1: F811 redefinition of unused 'test_keystroke_0s_cbreak_noinput' from line 148
    test_full_keyboard.py:733:1: F811 redefinition of unused 'test_keystroke_0s_cbreak_noinput_nokb' from line 161
    test_full_keyboard.py:746:1: F811 redefinition of unused 'test_keystroke_1s_cbreak_noinput' from line 174
    test_full_keyboard.py:761:1: F811 redefinition of unused 'test_keystroke_1s_cbreak_noinput_nokb' from line 189